name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608  # v4.1.0
    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236  # v4.7.1
    - run: python -m pip install --upgrade pip
    - run: python -m pip install -e ".[test]"
    - name: Lint
      run: pre-commit run --all-files
    - name: Test
      run: pytest
